name: "Build"

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev
          sudo python3 -m pip install meson
          sudo python3 -m pip install ninja
      - name: Configure Waf
        run: |
          python3 waf --out=build_waf distclean configure
      - name: Build & Test Waf
        run: |
          python3 waf --out=build_waf build
      - name: Configure Meson
        run: |
          meson setup build_meson
      - name: Build Meson
        run: |
          meson compile -C build_meson
      - name: Test Meson
        run: |
          meson test -C build_meson
