name: "Build"

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcmocka-dev
      - name: Configure
        run: |
          python3 waf distclean configure
      - name: Build
        run: |
          python3 waf build
